global:
  namespace: retail
  environment: prod

ui:
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

catalog:
  replicas: 2
  persistence:
    provider: dynamodb

carts:
  replicas: 2
  persistence:
    provider: dynamodb

orders:
  replicas: 2
  persistence:
    provider: postgres

checkout:
  replicas: 2
  cache:
    provider: redis

observability:
  prometheusMetrics: true
  otelTracing: true
